# Generated by Django 3.1.5 on 2021-01-29 02:06

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('diary', '0005_categorylist_donelist'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DoneList',
            new_name='Done',
        ),
    ]
