# Generated by Django 3.1.5 on 2021-01-31 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0002_auto_20210126_2141'),
    ]

    operations = [
        migrations.AlterField(
            model_name='position',
            name='order',
            field=models.CharField(choices=[('1', 1), ('2', 2), ('3', 3), ('4', 4), ('5', 5)], max_length=1, verbose_name='順位'),
        ),
    ]
